// English translations — used as fallback when lang is not "zh"
const en = {
  // Top bar
  toggleSidebar: "Toggle sidebar",
  panelLayout: "Panel layout",
  search: "Search",
  back: "Back",
  forward: "Forward",
  settings: "Settings",
  customize: "Customize",

  // Sidebar
  dswork: "Dswork",
  code: "Code",
  newTask: "New task",
  newSession: "New session",
  projects: "Projects",
  scheduled: "Scheduled",
  liveArtifacts: "Live artifacts",
  searchSessions: "Search sessions",
  searchTasks: "Search tasks",
  pinned: "Pinned",
  recents: "Recents",
  clearSearch: "Clear search",
  pin: "Pin",
  unpin: "Unpin",
  rename: "Rename",
  markDone: "Mark done",
  markActive: "Mark active",
  archive: "Archive",
  moreActions: "More actions",
  deepseekChat: "DeepSeek chat",
  codeWorkspace: "Code workspace",

  // Profile menu
  language: "Language",
  moreLanguagesSoon: "More languages coming soon",
  thirdPartyModels: "Third-party models",
  comingSoon: "Coming soon",
  checkUpdates: "Check for updates",
  latestVersion: "You're running the latest version of NextAgent.",
  learnDeepSeek: "Learn about DeepSeek",
  resetNextAgent: "Reset NextAgent",
  enableAgentMode: "Enable Agent mode in Settings",

  // Dswork home
  whatCanIHelp: "What can I help you with?",
  homeDesc: "Chat, brainstorm, write, and explore ideas directly with DeepSeek.",
  howCanIHelp: "How can I help you today?",
  workInProject: "Work on a project",
  active: "Active",
  clearActive: "Clear active",
  conversationStarted: "Conversation started.",
  justNow: "Just now",
  inProgress: "In progress",
  attachContext: "Attach context",
  sendTask: "Send work task",

  // Conversation
  thinking: "DeepSeek is thinking…",
  writeMessage: "Write a message…",
  queued: "Queued",
  queue: "Queue",
  moreOptions: "More options",
  attachFiles: "Attach files",
  stopResponse: "Stop response",

  // Status
  running: "Running",
  failed: "Failed",
  stopped: "Stopped",
  idle: "Idle",
  complete: "Complete",

  // Loading
  startupFailed: "Startup check failed",
  starting: "Starting NextAgent",
  checkingCore: "Checking core files and DeepSeek API connection…",
  checkAgain: "Check again",
  updateApiKey: "Update API key",

  // Setup
  welcome: "Welcome to NextAgent",
  setupDesc: "Connect your DeepSeek account to start coding with the local NextAgent core.",
  apiKey: "DeepSeek API key",
  keyStoredLocal: "Your key is stored only on this Windows device.",
  hideKey: "Hide API key",
  showKey: "Show API key",
  checking: "Checking…",
  continue: "Continue",
  keyNeverLeaves: "Your API key never leaves the local NextAgent core.",

  // Code Dashboard
  whatsNext: "What's next?",
  coreRunning: "Core running",
  coreConnected: "Core connected",
  apiKeyNeeded: "API key needed",
  coreOffline: "Core offline",
  coreError: "Core error",
  latestResponse: "Latest response",
  overview: "Overview",
  models: "Models",
  sessions: "Sessions",
  messages: "Messages",
  totalTokens: "Total tokens",
  promptTokens: "Prompt tokens",
  outputTokens: "Output tokens",
  cacheHit: "Cache hit",
  cachedTokens: "Cached tokens",
  saved: "Saved",
  noModelActivity: "No model activity yet",
  statsParagraph: (total, rate) => `NextAgent core has processed ${total} tokens with an average prefix cache hit rate of ${rate}%.`,

  // Code conversation
  working: "Working",
  taskFailed: "Task failed",
  completed: "Completed",
  deepseekInspecting: "DeepSeek is inspecting the workspace and working on your request…",
  thinkingStage: "Thinking stage",
  toolCall: "tool call",
  stageUnderstanding: "Understood the request",
  stageContext: "Checked the conversation context",
  stageComposing: "Drafting a concise response",
  stageResponse: "Prepared the final response",
  traceRunning: "Running",
  traceNoTools: "No tool calls",
  traceNoToolsDesc: "This answer was produced without calling external tools.",
  traceTool: (name) => `Tool: ${name}`,

  // Code composer
  describeTask: "Describe a task or ask a question",
  runEnvironment: "Run environment",
  remoteLater: "Remote environments coming soon",
  openFolder: "Open folder…",
  searchBranches: "Search branches…",
  local: "Local",
  recent: "Recent",
  addFolderToSession: "Add folder to session",
  addFilesOrPhotos: "Add files or photos",
  addFolder: "Add folder",
  importGitHub: "Import GitHub issue",
  slashCommands: "Slash commands",
  addConnectors: "Add connectors",
  addPlugins: "Add plugins…",
  enterToSend: "Enter to send · Shift+Enter for newline",
  askPermissions: "Ask permissions",
  acceptEdits: "Accept edits",
  planMode: "Plan mode",
  bypassPermissions: "Bypass permissions",
  enterToSendHint: "Enter to send · Shift+Enter for newline",

  // Effort menu
  effort: "Effort",
  faster: "Faster",
  smarter: "Smarter",
  low: "Low",
  medium: "Medium",
  high: "High",
  max: "Max",

  // Slash commands
  noMatchingCmds: "No matching commands",
  typeToFilter: "Type to filter",

  // Directory
  directory: "Directory",
  closeDirectory: "Close directory",
  plugins: "Plugins",
  connectors: "Connectors",
  skills: "Skills",
  noMatch: (section, search) => `No ${section} matching "${search}"`,
  notAvailable: (section) => `No ${section} yet`,
  pluginsDesc: "Plugins will appear here once the NextAgent plugin registry is connected.",
  connectorsDesc: "Connectors will appear here once integrations are available.",

  // Reset
  resetTitle: "Reset NextAgent?",
  resetDesc: "This will permanently delete all recents, conversations, agent memory, token usage, and your saved DeepSeek API key.",
  cancel: "Cancel",
  resetBtn: "Reset NextAgent",
  relaunching: (s) => s > 0 ? `Relaunching in ${s}s` : "Resetting NextAgent",
  relaunchClearing: "Clearing local data and returning to DeepSeek API setup…",
  relaunchPreparing: "Preparing a fresh NextAgent setup…",

  // Feature pages
  searchProjects: "Search projects…",
  searchScheduledTasks: "Search scheduled tasks…",
  newProject: "New project",
  newScheduledTask: "New scheduled task",
  newArtifact: "New live artifact",
  delete: "Delete",
  runNow: "Run now",
  pause: "Pause",
  enable: "Enable",
  dailyBrief: "Daily brief",
  weeklyReview: "Weekly review",
  createFirst: (thing) => `Create your first ${thing}`,

  // Customize page
  backToWorkspace: "Back to workspace",
  customizeNextAgent: "Customize NextAgent",
  customizeDesc: "Skills, connectors, and plugins shape how NextAgent works.",
  connectApps: "Connect your apps",
  connectAppsDesc: "Let NextAgent read and write on the tools you already use.",
  createSkills: "Create new skills",
  createSkillsDesc: "Teach NextAgent your workflows, team conventions, and expertise.",
  browsePlugins: "Browse plugins",
  browsePluginsDesc: "Add pre-built knowledge for your domain.",
  add: (section) => `Add ${section.slice(0, -1)}`,
  personalPlugins: "Personal plugins",
  giveExpertise: "Give NextAgent role-level expertise through plugins",

  // Settings page
  general: "General",
  privacy: "Privacy",
  capabilities: "Capabilities",
  nextAgent: "NextAgent",
  collaboration: "Collaboration",
  behavior: "Behavior",
  launchMode: "Launch mode",
  launchModeDesc: "Choose which workspace appears after launch.",
  enterToSend: "Enter to send",
  enterToSendDesc: "Press Enter to send, Shift+Enter for newline.",
  recentDetails: "Recent details",
  recentDetailsDesc: "Show model and status in recents list.",
  interfaceLanguage: "Interface language",
  interfaceLanguageDesc: "More languages will be added in upcoming releases.",
  localMemory: "Local memory",
  conversationMemory: "Conversation memory",
  conversationMemoryDesc: "Keep conversations in recents across restarts.",
  userMemory: "User memory",
  userMemoryDesc: "Allow Agent mode to remember preferences and helpful corrections.",
  localTokenStats: "Local token stats",
  localTokenStatsDesc: "Store token usage and cache stats only on this device.",
  localByDefault: "Local by default",
  localByDefaultDesc: "NextAgent stores settings, memory, and API credentials on this Windows device. Third-party model access is not enabled.",
  agent: "Agent",
  agentMode: "Agent mode",
  agentModeDesc: "Enable code workspace, tools, file editing, shell commands, and multi-step tasks.",
  skillsSettings: "Skills",
  skillsSettingsDesc: "Skills guide Agent mode with specialized workflows.",
  appearance: "Appearance",
  background: "Background",
  backgroundDesc: "Choose your workspace canvas color.",
  density: "Density",
  densityDesc: "Adjust spacing throughout your workspace.",
  reduceMotion: "Reduce motion",
  reduceMotionDesc: "Minimize transitions and animations.",
  warm: "Warm",
  white: "White",
  blueMist: "Blue mist",
  comfortable: "Comfortable",
  compact: "Compact",
  deepseekConnection: "DeepSeek connection",
  connectedLocally: "Connected locally",
  notConfigured: "Not configured",
  collaborationComing: "Collaboration features coming soon",
  collaborationDesc: "Shared workspaces, team memory, and collaborative agent sessions will be here.",
  notYetAvailable: "Not yet available",
  appearancePreview: "NextAgent workspace",
  appearancePreviewDesc: "Your appearance changes apply instantly.",

  // Action strings
  responseStopped: "Response stopped.",
  tip: "you can drag chats here to pin them",
  create: "Create",
  save: "Save",
  savedVersions: (n) => `${n} saved versions`,
  saveNewVersion: "Save new version",
  close: "Close",
  sortBy: "Sort by",
  name: "Name",
  recentActivity: "Recent activity",
  nextRun: "Next run",
  noMatchingProjects: "No matching projects",
  noMatchingScheduledTasks: "No matching scheduled tasks",
  noMatchingArtifacts: "No matching live artifacts",
  startProjectTitle: "Looking to start a project?",
  startProjectBody: "Give NextAgent a folder you already work from",
  scheduledDesc: "Run tasks on a schedule or whenever you need them. Type /schedule in any existing task to set one up.",
  awakeOnly: "Scheduled tasks only run while your computer is awake.",
  keepAwake: "Keep awake",
  enabled: "Enabled",
  paused: "Paused",
  runningNow: "Running now...",
  lastRan: (time) => `Last ran ${time}`,
  runNotice: (name) => `Ran "${name}" with DeepSeek.`,
  failedWith: (message) => `Failed: ${message}`,
  liveArtifactsDesc: "Create dynamic artifacts that stay up-to-date using live data from your connectors.",
  openLiveView: "Open live view",
  refresh: "Refresh",
  createFirstArtifact: "Create your first artifact",
  whatNeedsAttention: "What needs my attention",
  createLabel: (label) => `Create ${label}`,
  projectLabel: "project",
  scheduledLabel: "scheduled task",
  artifactLabel: "live artifact",
  projectCreateDesc: "Projects keep their own folder, context, instructions, and memory.",
  scheduledCreateDesc: "Scheduled tasks can run repeatedly or whenever you choose Run now.",
  artifactCreateDesc: "Live artifacts are persistent interactive HTML views you can refresh and edit.",
  localFolder: "Local folder",
  chooseExistingFolder: "Choose an existing folder",
  choose: "Choose",
  schedule: "Schedule",
  html: "HTML",
  nameYour: (label) => `Name your ${label}`,
  liveArtifactDefaultHtml: "<!doctype html><html><body style='font-family:system-ui;padding:32px'><h1>NextAgent live artifact</h1><p>Edit this HTML to build a live dashboard.</p></body></html>",
  searchSection: (section) => `Search ${section.toLowerCase()}...`,
  localSkill: "Local NextAgent skill",
  localPluginDesc: "Local role-level expertise for NextAgent",
  customPlugin: "Custom plugin",
  noneYet: (section) => `No ${section.toLowerCase()} yet.`,
  createSkill: "Create a skill",
  addConnector: "Add a connector",
  skillEditorDesc: "Skills teach NextAgent a repeatable process and are loaded by the core.",
  connectorEditorDesc: "Add a custom app or MCP endpoint for this workspace.",
  description: "Description",
  connectorUrl: "Connector URL",
  skillPlaceholder: "When and why NextAgent should use it",
  instructions: "Instructions",
  instructionPlaceholder: "Describe the workflow NextAgent should follow.",
  createdSkillNotice: (name) => `Created skill "${name}".`,
  connectedNotice: (name) => `Connected "${name}".`,
  settingsGeneralDesc: "Choose how NextAgent behaves day to day.",
  settingsPrivacyDesc: "Control what NextAgent remembers on this device.",
  settingsCapabilitiesDesc: "Manage Agent mode and the skills available to it.",
  settingsNextAgentDesc: "Shape the look and feel of your workspace.",
  settingsCollaborationDesc: "Work together with shared agents and projects.",
  currentLanguage: "English",
  activeSkill: "Active",

  // Code mode context pills
  worktree: "Worktree",
  file: " file",
  files: " files",
};

export default en;
