const zh = {
  // Top bar
  toggleSidebar: "切换侧边栏",
  panelLayout: "面板布局",
  search: "搜索",
  back: "后退",
  forward: "前进",
  settings: "设置",
  customize: "自定义",

  // Sidebar
  dswork: "工作区",
  code: "代码",
  newTask: "新建任务",
  newSession: "新建会话",
  projects: "项目",
  scheduled: "定时任务",
  liveArtifacts: "实时组件",
  searchSessions: "搜索会话",
  searchTasks: "搜索任务",
  pinned: "已固定",
  recents: "最近",
  clearSearch: "清除搜索",
  pin: "固定",
  unpin: "取消固定",
  rename: "重命名",
  markDone: "标记完成",
  markActive: "标记激活",
  archive: "归档",
  moreActions: "更多操作",
  deepseekChat: "DeepSeek 对话",
  codeWorkspace: "代码工作区",

  // Profile menu
  language: "语言",
  moreLanguagesSoon: "更多语言即将推出",
  thirdPartyModels: "第三方模型",
  comingSoon: "即将推出",
  checkUpdates: "检查更新",
  latestVersion: "你正在运行最新版本的 NextAgent。",
  learnDeepSeek: "了解 DeepSeek",
  resetNextAgent: "重置 NextAgent",
  enableAgentMode: "在设置中启用 Agent 模式",

  // Dswork home
  whatCanIHelp: "有什么可以帮你？",
  homeDesc: "与 DeepSeek 直接对话、头脑风暴、写作和探索想法。",
  howCanIHelp: "今天有什么可以帮你？",
  workInProject: "在项目中工作",
  active: "进行中",
  clearActive: "清除进行中",
  conversationStarted: "对话已开始。",
  justNow: "刚刚",
  inProgress: "进行中",
  attachContext: "附加上下文",
  sendTask: "发送任务",

  // Conversation
  thinking: "DeepSeek 正在思考...",
  writeMessage: "输入消息...",
  queued: "排队中",
  queue: "排队",
  moreOptions: "更多选项",
  attachFiles: "附加文件",
  stopResponse: "停止回复",

  // Status
  running: "运行中",
  failed: "失败",
  stopped: "已停止",
  idle: "空闲",
  complete: "完成",

  // Loading
  startupFailed: "启动检查失败",
  starting: "正在启动 NextAgent",
  checkingCore: "正在检查核心文件和 DeepSeek API 连接...",
  checkAgain: "重新检查",
  updateApiKey: "更新 API 密钥",

  // Setup
  welcome: "欢迎使用 NextAgent",
  setupDesc: "连接你的 DeepSeek 账户，开始使用本地 NextAgent 核心进行编码。",
  apiKey: "DeepSeek API 密钥",
  keyStoredLocal: "你的密钥仅存储在此 Windows 设备上。",
  hideKey: "隐藏 API 密钥",
  showKey: "显示 API 密钥",
  checking: "检查中...",
  continue: "继续",
  keyNeverLeaves: "你的 API 密钥不会离开本地 NextAgent 核心。",

  // Code Dashboard
  whatsNext: "接下来做什么？",
  coreRunning: "核心运行中",
  coreConnected: "核心已连接",
  apiKeyNeeded: "需要 API 密钥",
  coreOffline: "核心离线",
  coreError: "核心错误",
  latestResponse: "最新回复",
  overview: "概览",
  models: "模型",
  sessions: "会话",
  messages: "消息",
  totalTokens: "总 Token",
  promptTokens: "输入 Token",
  outputTokens: "输出 Token",
  cacheHit: "缓存命中",
  cachedTokens: "缓存 Token",
  saved: "节省",
  noModelActivity: "暂无模型活动",
  statsParagraph: (total, rate) => `NextAgent 核心已处理 ${total} 个 Token，平均前缀缓存命中率 ${rate}%。`,

  // Code conversation
  working: "工作中",
  taskFailed: "任务失败",
  completed: "已完成",
  deepseekInspecting: "DeepSeek 正在检查工作区并处理你的请求...",

  // Code composer
  describeTask: "描述任务或提问",
  runEnvironment: "运行环境",
  remoteLater: "远程环境即将推出",
  openFolder: "打开文件夹...",
  searchBranches: "搜索分支...",
  local: "本地",
  recent: "最近",
  addFolderToSession: "添加文件夹到会话",
  addFilesOrPhotos: "添加文件或照片",
  addFolder: "添加文件夹",
  importGitHub: "导入 GitHub 问题",
  slashCommands: "斜杠命令",
  addConnectors: "添加连接器",
  addPlugins: "添加插件...",
  enterToSend: "Enter 发送 · Shift+Enter 换行",
  askPermissions: "询问权限",
  acceptEdits: "接受编辑",
  planMode: "规划模式",
  bypassPermissions: "绕过权限",

  // Effort menu
  effort: "执行力度",
  faster: "更快",
  smarter: "更智能",
  low: "低",
  medium: "中",
  high: "高",
  max: "最高",

  // Slash commands
  noMatchingCmds: "无匹配命令",
  typeToFilter: "输入筛选",

  // Directory
  directory: "目录",
  closeDirectory: "关闭目录",
  plugins: "插件",
  connectors: "连接器",
  skills: "技能",
  noMatch: (section, search) => `没有匹配"${search}"的${section}`,
  notAvailable: (section) => `暂无${section}`,
  pluginsDesc: "插件将在 NextAgent 插件注册表连接后出现在此处。",
  connectorsDesc: "连接器将在集成可用后出现在此处。",

  // Reset
  resetTitle: "重置 NextAgent？",
  resetDesc: "这将永久删除所有最近记录、对话、Agent 记忆、Token 使用量和已保存的 DeepSeek API 密钥。",
  cancel: "取消",
  resetBtn: "重置 NextAgent",
  relaunching: (s) => s > 0 ? `将在 ${s} 秒后重新启动` : "正在重置 NextAgent",
  relaunchClearing: "正在清除本地数据并返回 DeepSeek API 设置...",
  relaunchPreparing: "正在准备全新的 NextAgent 设置...",

  // Feature pages
  searchProjects: "搜索项目...",
  searchScheduledTasks: "搜索定时任务...",
  newProject: "新建项目",
  newScheduledTask: "新建定时任务",
  newArtifact: "新建实时组件",
  openFolder: "打开文件夹",
  delete: "删除",
  runNow: "立即运行",
  pause: "暂停",
  enable: "启用",
  dailyBrief: "每日简报",
  weeklyReview: "每周回顾",
  createFirst: (thing) => `创建你的第一个${thing}`,

  // Customize page
  backToWorkspace: "返回工作区",
  customizeNextAgent: "自定义 NextAgent",
  customizeDesc: "技能、连接器和插件塑造 NextAgent 的工作方式。",
  connectApps: "连接你的应用",
  connectAppsDesc: "让 NextAgent 在你已经使用的工具上读写。",
  createSkills: "创建新技能",
  createSkillsDesc: "教会 NextAgent 你的流程、团队规范和专业知识。",
  browsePlugins: "浏览插件",
  browsePluginsDesc: "为你的领域添加预构建的知识。",
  add: (section) => `添加${section.slice(0, -1)}`,
  personalPlugins: "个人插件",
  giveExpertise: "通过插件赋予 NextAgent 角色级别的专业知识",

  // Settings page
  general: "通用",
  privacy: "隐私",
  capabilities: "能力",
  nextAgent: "NextAgent",
  collaboration: "协作",
  behavior: "行为",
  launchMode: "启动模式",
  launchModeDesc: "选择启动后显示的工作区。",
  enterToSend: "Enter 发送",
  enterToSendDesc: "按 Enter 发送，Shift+Enter 换行。",
  recentDetails: "最近详情",
  recentDetailsDesc: "在最近列表中显示模型和状态。",
  interfaceLanguage: "界面语言",
  interfaceLanguageDesc: "更多语言将在未来版本中添加。",
  localMemory: "本地记忆",
  conversationMemory: "对话记忆",
  conversationMemoryDesc: "重启后保留最近列表中的对话。",
  userMemory: "用户记忆",
  userMemoryDesc: "允许 Agent 模式记住偏好和有用的纠正。",
  localTokenStats: "本地 Token 统计",
  localTokenStatsDesc: "仅在此设备上存储 Token 使用量和缓存统计。",
  localByDefault: "默认本地",
  localByDefaultDesc: "NextAgent 将设置、记忆和 API 凭证存储在此 Windows 设备上。未启用第三方模型访问。",
  agent: "Agent",
  agentMode: "Agent 模式",
  agentModeDesc: "启用代码工作区、工具、文件编辑、Shell 命令和多步骤任务。",
  skillsSettings: "技能",
  skillsSettingsDesc: "技能用专业工作流引导 Agent 模式。",
  appearance: "外观",
  background: "背景",
  backgroundDesc: "选择工作区画布颜色。",
  density: "界面密度",
  densityDesc: "调整整个工作区中的间距。",
  reduceMotion: "减少动画",
  reduceMotionDesc: "最小化过渡和动画效果。",
  warm: "暖色",
  white: "白色",
  blueMist: "蓝色薄雾",
  comfortable: "舒适",
  compact: "紧凑",
  deepseekConnection: "DeepSeek 连接",
  connectedLocally: "本地已连接",
  notConfigured: "未配置",
  collaborationComing: "协作功能即将推出",
  collaborationDesc: "共享工作区、团队记忆和协作 Agent 会话将在此处。",
  notYetAvailable: "尚未可用",
  appearancePreview: "NextAgent 工作区",
  appearancePreviewDesc: "你的外观更改会立即应用。",

  // Action strings
  responseStopped: "回复已停止。",
  tip: "提示：你可以将对话拖到这里来固定它们",
  create: "创建",
  save: "保存",
  savedVersions: (n) => `${n} 个已保存版本`,
  saveNewVersion: "保存新版本",
  close: "关闭",

  // Code mode context pills  
  worktree: "工作树",
  file: "个文件",
  files: "个文件",
};

export default zh;
